### ISSUE TITLE
Provide symlink for `musl-gcc`?

### ISSUE THREAD

**Issue by WesleyAC** [FiloSottile/homebrew-musl-cross#16]
Many scripts expect the command `musl-gcc` to exist. Making a symlink in my `$PATH` from `musl-gcc` to `$(which x86_64-linux-musl-gcc)` caused scripts that have this expectation to work. Seems like it'd be useful to provide this by default?

**Comment by FiloSottile** [comment]
I am not sure we should assume x86_64 like that. Is there a convention around it, @richfelker?

**Comment by richfelker** [comment]
I don't think it's a good idea for scripts to assume `musl-gcc`, or to symlink it to cross compilers. That's the wrapper script shipped for minimal out-of-the-box use of musl on a glibc host without actually installing a proper toolchain, and its arch corresponds to whatever arch your glibc-based host is, i.e. it's a "native" compiler not a cross one.

**Comment by FiloSottile** [comment]
In that sense though doesn't it do the same thing that `x86_64-linux-musl-gcc` does on an x86_64 macOS?

**Comment by richfelker** [comment]
Semantically, `musl-gcc` matching the wrapper shipped with musl would produce musl-linked binaries that you could run on your Mac, which isn't a thing. `x86_64-linux-musl-gcc` on the other hand is a cross compiler that produces musl-linked binaries to run on x86_64 Linux.

**Comment by FiloSottile** [comment]
Fair enough, it sounds like these scripts might get confused if they can't then run the binaries they compiled, and users might want to target different architectures at that point. We'll let them explicitly symlink `/usr/local/bin/musl-gcc` to `/usr/local/opt/musl-cross/bin/x86_64-linux-musl-gcc` if they wish.

**Comment by Oliboy50** [comment]
@FiloSottile I almost gave up on trying to compile to `x86_64-unknown-linux-musl` from "macOS Mojave", until I randomly try this small note from [an article on AWS blog](https://aws.amazon.com/fr/blogs/opensource/rust-runtime-for-aws-lambda/)

> On my system, some of the dependencies did not pick up the configured linker automatically and tried to use musl-gcc anyway. To get around this quickly, I simply created a symlink to the new linker:

> $ ln -s /usr/local/bin/x86_64-linux-musl-gcc /usr/local/bin/musl-gcc


Now I can finally use `FiloSottile/homebrew-musl-cross` as expected. Without the symlink stuff, the `ring` dependency of `rustls-tls` failed to compile.

I'd suggest to copy [your previous comment](https://github.com/FiloSottile/homebrew-musl-cross/issues/16#issuecomment-602292694) in the README of this repository, because it seems like **really important to know** for ppl which just want to make things work quickly.

Thank you
